### PR TITLE
Bump to 4.13.0

### PR DESCRIPTION
**Pull request by bf4**

### CODE REVIEW

**Comment by bf4** [comment]
I'll take a look at the failures.  The config hasn't gotten a little unwieldy

**Comment by etagwerker** [comment]
@bronzdoc Just rebased this PR with master. I think it would be a good idea to ship a release one we have the test suite passing in both Appveyor and Travis.

**Comment by olleolleolle** [comment]
@etagwerker @bronzdoc Would this be a good time to let go of unsupported Ruby versions in the _next_ version?

**Comment by etagwerker** [comment]
@olleolleolle I think that's a good idea. We should probably simplify `Gemfile` and remove references to EOLed ruby versions.

**Pull request merged**
