### PR TITLE
Feature/windows ci

### LINKED ISSUE #284: Verify Windows support
Create CI build on Windows.

Travis CI does not yet offer Windows builds, so we need to setup a new CI on https://ci.appveyor.com

### PR DESCRIPTION
**Pull request by bergholdt**
Setup CI pipeline on AppVeyor and fixed specs.

Fix #284

### CODE REVIEW

**Comment by bergholdt** [comment]
AppVeyor builds OK on my fork, but fails on main repo. It does not see PR or branch feature/windows-ci.

https://ci.appveyor.com/project/bergholdt/metric-fu
https://ci.appveyor.com/project/bergholdt/metric-fu-cfbfx

Perhaps CI project need to be create by owner of organization

**Comment by bf4** [comment]
@bergholdt do you need help setting this up?

**Comment by bergholdt** [comment]
@bf4 yes I need help. I'm not able to trigger builds on this repo, only my own fork https://ci.appveyor.com/project/bergholdt/metric-fu/build/1.0.4

**Comment by bf4** [comment]
I think I just set this up with access for you.

**Comment by jkeam** [comment]
Need any help getting this PR ready to merge?

**Comment by bergholdt** [comment]
All build passed 😊

Will remove bundle env, it's properly to verbose...extra commit will also show how much bundle caching helps

**Comment by bergholdt** [comment]
cache did not have any effect - must be using it wrong :-(

I think it's ready for merge - will you do it @jkeam

**Pull request merged**
