### PR TITLE
Upgrade churn

### PR DESCRIPTION
**Pull request by jkeam**
Update version of churn

### CODE REVIEW

**Comment by jkeam** [comment]
I was unable to reproduce https://github.com/metricfu/metric_fu/issues/277 but worth updating our very old version of churn anyways. 

Also hoping it fixes @trejkaz's issue.

**Comment by jkeam** [comment]
Thoughts on this?  Ok to merge?

**Comment by jkeam** [comment]
Would anyone object to this being merged in?

**Comment by pboling** [comment]
onward and upward!

**Comment by danmayer** [comment]
Hey, all awesome to see some activity on metric-fu... I haven't been doing much on churn lately, but I fixed a few issues at the 1.x jump... So I recommend the latest version. If anything in churn is causing issues please ping me on GitHub or twitter `@danmayer`  I expect all the basics that metric-fu should work back till Ruby 2.3, while newer features like class and method churn are a bit less reliable. I am glad it is still working for y'all and this project, and I would love to be a bit more active if you all need anything.

**Comment by bronzdoc** [comment]
Thanks for the heads up @danmayer!

**Pull request merged**
