### PR TITLE
Add reek line numbers to output

### PR DESCRIPTION
**Pull request by ggallen**
I've made changes to add the reek line numbers to the metric_fu output. These changes are localized to reek/generator.vb.

### CODE REVIEW

**Comment by MGotink** [comment]
I like the change, but could you rebase it to clean up the commit history and can you make the tests pass?

**Comment by ggallen** [comment]
Sure. I'll get it done.

**Comment by ggallen** [comment]
I am not a ruby expert.  Can you give me a quick primer on how to run the tests locally right in my metric_fu source tree?

**Comment by MGotink** [comment]
```bundle exec rspec```
See also [here](https://github.com/metricfu/metric_fu/blob/master/CONTRIBUTING.md)

**Comment by ggallen** [comment]
I'm going to pull this and create a new pull request.

**Pull request closed without merging**
