### PR TITLE
Fix simplecov missing logger dependency

### PR DESCRIPTION
**Pull request by MGotink**
See #235.

### CODE REVIEW

**Comment by bf4** [comment]
Thank you! :rainbow:

**Comment by bf4** [comment]
I haven't run this locally but I trust you to merge if it's good.

**Comment by MGotink** [comment]
All done, can we release a new gem version?

**Comment by bf4** [comment]
Yes.  I'll give you push if you want and sync up with what i do to
release.  Bother me if I don't do this tonight

**Comment by MGotink** [comment]
It's time to bother you :)

**Comment by bf4** [comment]
Zzzzzzz

B mobile phone

On Mar 4, 2015, at 11:39 AM, Martin Gotink <notifications@github.com> wrote:

It's time to bother you :)

—
Reply to this email directly or view it on GitHub
<https://github.com/metricfu/metric_fu/pull/250#issuecomment-77206207>.

**Pull request merged**
