### PR TITLE
Remove specific versions for guard dependencies 

### LINKED ISSUE #309: `bundle install` does not work with current version of `master`
Hi @bf4,

This is one of the issues I solved in #306. 

## Steps to Reproduce 

1. git clone 
2. bundle install 

## Error 

```
$ bundle
NOTE: Gem::Specification#default_executable= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#default_executable= called from /Users/etagwerker/Projects/fastruby/metric_fu/metric_fu.gemspec:37.
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
Gem::Specification#has_rdoc= called from /Users/etagwerker/Projects/fastruby/metric_fu/metric_fu.gemspec:40.
The dependency jruby-openssl (~> 0.9.17) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    guard-bundler (~> 1.0.0) was resolved to 1.0.0, which depends on
      bundler (~> 1.0)

  Current Bundler version:
    bundler (2.0.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (~> 1.0)', which is required by gem 'guard-bundler (~> 1.0.0)', in any of the sources.

Bundler could not find compatible versions for gem "guard":
  In Gemfile:
    guard (~> 1.8.1)

    guard-bundler (~> 1.0.0) was resolved to 1.0.0, which depends on
      guard (~> 1.1)

    guard-rspec was resolved to 1.2.2, which depends on
      guard (>= 1.1)

Bundler could not find compatible versions for gem "rb-inotify":
  In Gemfile:
    rb-inotify (~> 0.9.0)

    listen (~> 1.3.0) was resolved to 1.3.1, which depends on
      rb-inotify (>= 0.9)

Bundler could not find compatible versions for gem "rspec":
  In Gemfile:
    rspec (~> 3.1)

    guard-rspec was resolved to 2.5.4, which depends on
      rspec (~> 2.11)
```

A quick solution would be to remove the `guard` group from the `Gemfile` 

What do you think?

### PR DESCRIPTION
**Pull request by etagwerker**
Hey @bf4, 

This fixes #309. It is a commit extracted from #306, 

Please check it out.

Thanks!

### CODE REVIEW

**Comment by bf4** [comment]
I mean, the PR description is wrong.  The PR diff I see removes guard altogethr

**Comment by etagwerker** [comment]
@bf4 To be honest, I don't know why those dependencies are being installed in Travis CI or Appveyor. They are development dependencies meant for maintainers and contributors to use them, right? 

Either way, I changed the title of the PR to better represent the changes in this PR. It fixes the issue I saw when trying to initially setup my dev environment with this gem. 

I think it would be best to **not** install the `guard` group in Appveyor and Travis CI as it introduces another thing that can fail in those environments and it is not really needed there. 

The Travis CI will continue to fail until #308 is merged. 🤷‍♂

**Comment by bf4** [comment]
they shouldn't be installed on CI. I agree.

in the travis.yml we have

```
  - bundle config --local without local_development yard guard
```

I guess that's missing from appveyor

**Comment by etagwerker** [comment]
@bf4 There are many things wrong which are causing Appveyor to fail. The one you mentioned is one of them. I created #312 to keep track of that issue and patch.

**Comment by etagwerker** [comment]
@bf4 What do you suggest I do with this PR?

**Comment by bronzdoc** [comment]
Going to merge this since this dev dependencies should not be installed in CI and would help us keep moving forward setting a dev environment

**Pull request merged**
